export const industries =  [
  "Information Technology & Services",
  "Apparel & Fashion",
  "Farming",
  "Banking",
  "Judiciary",
  "Photography",
  "Airlines/Aviation",
  "Telecommunications",
  "Printing",
  "Machinery",
  "Textiles",
  "Hospitality",
  "Transportation/Trucking/Railroad",
  "Retail",
  "Construction",
  "Utilities",
  "Supermarkets",
  "Research",
  "Sports",
  "Internet",
  "Accounting",
  "Insurance",
  "Automotive",
  "Semiconductors",
  "Warehousing",
  "Restaurants",
  "Entertainment",
  "Cosmetics",
  "Chemicals",
  "Biotechnology",
  "Philanthropy",
  "Wholesale",
  "Design",
  "Ranching",
  "Libraries",
  "Dairy",
  "Newspapers",
  "Maritime",
  "Pharmaceuticals",
  "Military",
  "Outsourcing/Offshoring",
  "Fishery",
  "Furniture",
  "Animation",
  "Publishing",
  "Plastics",
  "Wireless",
  "Music",
  "E-learning",
  "Veterinary",
  "Shipbuilding",
  "Fundraising",
  "Tobacco",
  "Nanotechnology",
  "Think Tanks",
  "Public Relations & Communications",
  "Mechanical Or Industrial Engineering",
  "Import & Export",
  "Arts & Crafts",
  "Computer Hardware",
  "Electrical & Electronic Manufacturing",
  "Consumer Electronics",
  "Human Resources",
  "Civil Engineering",
  "Capital Markets",
  "Non-profit Organization Management",
  "Financial Services",
  "Packaging & Containers",
  "Computer Software",
  "Alternative Medicine",
  "Luxury Goods & Jewelry",
  "Consumer Services",
  "Industrial Automation",
  "Computer & Network Security",
  "Civic & Social Organization",
  "Facilities Services",
  "Medical Practice",
  "Primary/Secondary Education",
  "Staffing & Recruiting",
  "Broadcast Media",
  "Marketing & Advertising",
  "Health, Wellness & Fitness",
  "Logistics & Supply Chain",
  "Business Supplies & Equipment",
  "Real Estate",
  "Information Services",
  "Education Management",
  "Consumer Goods",
  "Food & Beverages",
  "Law Practice",
  "Government Administration",
  "Management Consulting",
  "Law Enforcement",
  "Building Materials",
  "Executive Office",
  "Political Organization",
  "Government Relations",
  "Renewables & Environment",
  "Investment Management",
  "Hospital & Health Care",
  "Glass, Ceramics & Concrete",
  "Higher Education",
  "Program Development",
  "Oil & Energy",
  "International Affairs",
  "Fine Art",
  "International Trade & Development",
  "Mining & Metals",
  "Medical Device",
  "Food Production",
  "Market Research",
  "Paper & Forest Products",
  "Computer Networking",
  "Defense & Space",
  "Writing & Editing",
  "Graphic Design",
  "Computer Games",
  "Environmental Services",
  "Security & Investigations",
  "Venture Capital & Private Equity",
  "Aviation & Aerospace",
  "Public Policy",
  "Events Services",
  "Public Safety",
  "Architecture & Planning",
  "Package/Freight Delivery",
  "Leisure, Travel & Tourism",
  "Commercial Real Estate",
  "Individual & Family Services",
  "Investment Banking",
  "Sporting Goods",
  "Professional Training & Coaching",
  "Legal Services",
  "Recreational Facilities & Services",
  "Legislative Office",
  "Religious Institutions",
  "Mental Health Care",
  "Online Media",
  "Wine & Spirits",
  "Media Production",
  "Performing Arts",
  "Motion Pictures & Film",
  "Museums & Institutions",
  "Translation & Localization",
  "Alternative Dispute Resolution",
  "Gambling & Casinos",
  "Information Technology & Services",
  "Railroad Manufacture"
]

export const prospect = [
  "Assistant Vice President",
  "Co-founder",
  "Director",
  "Chief Administrative Officer",
  "Chief Architect",
  "Chief Business Officer",
  "Chief Business Development Officer",
  "Chief Commercial Officer",
  "Chief Compliance Officer",
  "Chief Consultant",
  "Chief Creative Officer",
  "Chief Development Officer",
  "Chief Executive Officer",
  "Chief Financial Officer",
  "Chief Human Resources Officer",
  "Project Manager",
  "Lead Business Analyst",
  "Business Development Lead",
  "Business Process Lead",
  "Chief Product Officer",
  "Director Of Product Development",
  "Director Of Product Management",
  "Director Of Product Marketing",
  "Global Product Manager",
  "Group Product Manager",
  "Head Of Product Development",
  "Head Of Product Management",
  "Lead Product Manager",
  "Principal Product Manager",
  "Director Of Software Development",
  "Director Of Software Engineering",
  "Sales Representative",
  "Principal Chief Executive Officer",
  "Head Of Product",
  "Head Of Production",
  "Head Of Procurement"
]


export const countries = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", 
  "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", 
  "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", 
  "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", 
  "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", 
  "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)", "Costa Rica", 
  "Croatia", "Cuba", "Cyprus", "Czech Republic", "Democratic Republic of the Congo", 
  "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", 
  "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", 
  "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", 
  "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", 
  "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", 
  "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", 
  "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", 
  "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", 
  "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", 
  "Montenegro", "Morocco", "Mozambique", "Myanmar (formerly Burma)", "Namibia", "Nauru", 
  "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", 
  "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", 
  "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", 
  "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", 
  "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", 
  "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", 
  "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", 
  "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", 
  "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", 
  "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", 
  "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", 
  "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];


export const companiesSize = [
"0-1",
"2-10",
"11-50",
"51-200",
"201-500",
"501-1000",
"1001-5000",
"5001-10000",
"10000+",
]